"""Daily timing: an in-process daemon plus native installers for Windows and Ubuntu."""

from __future__ import annotations

import logging
import subprocess
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from .config import Config, TIME_PATTERN

log = logging.getLogger("evenews.scheduler")

TASK_NAME = "EveNews Daily Briefing"
CRON_MARKER = "# evenews daily briefing"


def _zone(name: str) -> ZoneInfo:
    try:
        return ZoneInfo(name)
    except (ZoneInfoNotFoundError, ValueError):
        return ZoneInfo("UTC")


def next_fire(
    now: datetime,
    *,
    time_of_day: str = "08:00",
    timezone: str = "Asia/Shanghai",
    weekday_only: bool = False,
) -> datetime:
    if not TIME_PATTERN.match(time_of_day):
        raise ValueError(f"schedule.time 需要 HH:MM 格式，当前为 {time_of_day}")
    hour, minute = (int(part) for part in time_of_day.split(":"))
    local = now.astimezone(_zone(timezone))
    target = local.replace(hour=hour, minute=minute, second=0, microsecond=0)
    if target <= local:
        target += timedelta(days=1)
    while weekday_only and target.weekday() >= 5:
        target += timedelta(days=1)
    return target


def run_daemon(config: Config, job) -> None:
    """Long-running loop that fires the job at schedule.time (identical code on Windows and Ubuntu)."""
    zone = _zone(config.schedule.timezone)
    log.info(
        "守护进程已启动：每天 %s（%s%s）运行，Ctrl+C 退出",
        config.schedule.time,
        config.schedule.timezone,
        "，仅工作日" if config.schedule.weekday_only else "",
    )
    while True:
        target = next_fire(
            datetime.now(zone),
            time_of_day=config.schedule.time,
            timezone=config.schedule.timezone,
            weekday_only=config.schedule.weekday_only,
        )
        waiting = (target - datetime.now(zone)).total_seconds() / 3600
        log.info("下次运行：%s（%.1f 小时后）", target.strftime("%Y-%m-%d %H:%M"), waiting)
        while (target - datetime.now(zone)).total_seconds() > 0:
            time.sleep(min(60.0, max(1.0, (target - datetime.now(zone)).total_seconds())))
        try:
            job()
        except KeyboardInterrupt:
            raise
        except Exception:  # noqa: BLE001 - the daemon must survive a bad morning
            log.exception("本次运行失败，等待下一个周期")
        time.sleep(61)


def config_file(config: Config) -> Path:
    return Path(config.path or "config.yaml").resolve()


def project_dir(config: Config) -> Path:
    return config_file(config).parent


def log_file(config: Config) -> Path:
    return project_dir(config) / "logs" / "daily.log"


def run_argv(config: Config) -> list[str]:
    return [sys.executable, "-m", "evenews", "run", "--config", str(config_file(config))]


def windows_wrapper(config: Config) -> Path:
    """Wrapper script used by Task Scheduler: keeps the working directory and the log in one place."""
    root = project_dir(config)
    wrapper = root / "run_daily.cmd"
    root.joinpath("logs").mkdir(parents=True, exist_ok=True)
    body = [
        "@echo off",
        "rem Generated by `evenews install-task` - regenerate instead of editing by hand",
        f'cd /d "{root}"',
        f'"{sys.executable}" -m evenews run --config "{config_file(config)}" >> "{log_file(config)}" 2>&1',
    ]
    wrapper.write_text("\r\n".join(body) + "\r\n", encoding="gbk", errors="replace")
    return wrapper


def windows_task_command(config: Config) -> str:
    wrapper = windows_wrapper(config)
    return (
        f'schtasks /Create /F /TN "{TASK_NAME}" /SC DAILY /ST {config.schedule.time} '
        f'/TR "cmd /c \\"{wrapper}\\""'
    )


def install_windows_task(config: Config, *, apply: bool = True) -> str:
    command = windows_task_command(config)
    if not apply:
        return command
    completed = subprocess.run(command, shell=True, capture_output=True, text=True)
    output = ((completed.stdout or "") + (completed.stderr or "")).strip()
    if completed.returncode != 0:
        raise RuntimeError(f"schtasks 失败（部分改动需要管理员权限）：\n{command}\n{output}")
    return output or command


def cron_line(config: Config) -> str:
    time_of_day = config.schedule.time if TIME_PATTERN.match(config.schedule.time or "") else "08:00"
    hour, minute = time_of_day.split(":")
    days = "1-5" if config.schedule.weekday_only else "*"
    root = project_dir(config)
    command = " ".join(f"'{part}'" if " " in part else part for part in run_argv(config))
    return (
        f"{int(minute)} {int(hour)} * * {days} "
        f"cd {root} && {command} >> {log_file(config)} 2>&1"
    )


def install_cron(config: Config, *, apply: bool = True) -> str:
    try:
        current = subprocess.run("crontab -l", shell=True, capture_output=True, text=True).stdout or ""
    except Exception:  # noqa: BLE001 - cron may be missing entirely
        current = ""
    if "evenews run" in current:
        return "crontab 里已经有 evenews 任务，未重复添加（先 crontab -e 删除旧行）"
    proposed = current.rstrip("\n") + "\n" + CRON_MARKER + "\n" + cron_line(config) + "\n"
    if not apply:
        return proposed
    completed = subprocess.run("crontab -", shell=True, input=proposed, capture_output=True, text=True)
    if completed.returncode != 0:
        raise RuntimeError((completed.stderr or "crontab 安装失败").strip())
    return proposed


def systemd_service(config: Config) -> str:
    """Unit that runs the built-in daemon; the timer alternative is included as a comment."""
    config_path = config_file(config)
    root = project_dir(config)
    hour, minute = (config.schedule.time if TIME_PATTERN.match(config.schedule.time or "") else "08:00").split(":")
    on_calendar = ("Mon-Fri " if config.schedule.weekday_only else "") + f"*-*-* {int(hour):02d}:{int(minute):02d}:00"
    return f"""# /etc/systemd/system/evenews.service
[Unit]
Description=Eve_News daily AI briefing
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={root}
ExecStart={sys.executable} -m evenews daemon --config {config_path}
Restart=always
RestartSec=30
Environment=PYTHONUNBUFFERED=1
# 需要 .env 里的密钥时取消下一行注释
# EnvironmentFile={root}/.env

[Install]
WantedBy=multi-user.target
"""


def systemd_timer(config: Config) -> str:
    """Timer pair for people who prefer systemd cron over the built-in daemon."""
    config_path = config_file(config)
    root = project_dir(config)
    hour, minute = (config.schedule.time if TIME_PATTERN.match(config.schedule.time or "") else "08:00").split(":")
    on_calendar = ("Mon-Fri " if config.schedule.weekday_only else "") + f"*-*-* {int(hour):02d}:{int(minute):02d}:00"
    return f"""# /etc/systemd/system/evenews.service
[Unit]
Description=Eve_News daily AI briefing (one-shot)

[Service]
Type=oneshot
WorkingDirectory={root}
ExecStart={sys.executable} -m evenews run --config {config_path}
StandardOutput=append:{root}/logs/daily.log
StandardError=append:{root}/logs/daily.log

# /etc/systemd/system/evenews.timer
[Unit]
Description=Run Eve_News daily

[Timer]
OnCalendar={on_calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""


def daemon_hint(config: Config) -> str:
    return (
        "Windows 用 schtasks：evenews install-task\n"
        "Ubuntu 用 cron：evenews install-cron；或用 evenews systemd 生成 systemd 单元\n"
        "不想装计划任务就直接前台跑：evenews daemon（配 systemd / nssm / 开机自启）"
    )
